language: perl
dist: trusty
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
  - '5.28'
  - '5.30'
env:
  - DB_TESTING=1 RELEASE_TESTING=1 COVERAGE=1
services:
   - postgresql

before_install:
   - eval $(curl https://travis-perl.github.io/init) --auto

