language: perl
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
env:
  - DB_TESTING=1 RELEASE_TESTING=1
addons:
   postgresql: "9.3"
env:
before_install:
   - eval $(curl https://travis-perl.github.io/init) --auto

